package com.poultryguard.ai.data.repository

import android.content.Context
import android.util.Log
import com.poultryguard.ai.data.api.BatchApi
import com.poultryguard.ai.data.api.CloseBatchRequest
import com.poultryguard.ai.data.api.RecordMortalityRequest
import com.poultryguard.ai.data.api.StartBatchRequest
import com.poultryguard.ai.data.cache.AppDatabase
import com.poultryguard.ai.data.cache.LocalCacheManager
import com.poultryguard.ai.data.model.Batch
import com.poultryguard.ai.data.model.BatchStatus
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.OkHttpClient
import retrofit2.Retrofit
import retrofit2.converter.gson.GsonConverterFactory
import java.util.UUID
import java.util.concurrent.TimeUnit

class BatchRepository(private val context: Context) {

    private val cacheManager = LocalCacheManager(context)
    private val db = AppDatabase.getDatabase(context)
    private val mortalityDao = db.mortalityDao()

    private var currentUrl: String = ""
    private var cachedApi: BatchApi? = null

    private fun getApi(): BatchApi? {
        val url = cacheManager.getApiBaseUrl()
        if (url != currentUrl || cachedApi == null) {
            currentUrl = url
            cachedApi = try {
                val okHttpClient = OkHttpClient.Builder()
                    .connectTimeout(10, TimeUnit.SECONDS)
                    .readTimeout(15, TimeUnit.SECONDS)
                    .writeTimeout(15, TimeUnit.SECONDS)
                    .build()

                Retrofit.Builder()
                    .baseUrl(currentUrl)
                    .client(okHttpClient)
                    .addConverterFactory(GsonConverterFactory.create())
                    .build()
                    .create(BatchApi::class.java)
            } catch (e: Exception) {
                null
            }
        }
        return cachedApi
    }

    suspend fun startBatch(
        farmId: String,
        startDate: String,
        initialCount: Int,
        breed: String
    ): Result<Batch> = withContext(Dispatchers.IO) {
        try {
            val api = getApi() ?: throw Exception("API not initialized.")
            val autoGeneratedId = "BATCH-${System.currentTimeMillis()}"
            val request = StartBatchRequest(
                batchId = autoGeneratedId,
                startDate = startDate,
                initialCount = initialCount,
                breed = breed
            )
            val response = api.startBatch(farmId, request)
            if (response.status == "success" && response.data != null) {
                cacheManager.cacheActiveBatch(response.data)
                Result.success(response.data)
            } else {
                throw Exception(response.message ?: "Failed to start batch on backend.")
            }
        } catch (e: Exception) {
            Log.e("BatchRepository", "Error starting batch: ${e.localizedMessage}. Falling back to local/offline batch.")
            val autoGeneratedId = "BATCH-${System.currentTimeMillis()}"
            val localBatch = Batch(
                id = autoGeneratedId,
                farmId = farmId,
                startDate = startDate,
                endDate = null,
                initialCount = initialCount,
                currentCount = initialCount,
                breed = breed,
                status = BatchStatus.ACTIVE
            )
            cacheManager.cacheActiveBatch(localBatch)
            Result.success(localBatch)
        }
    }

    suspend fun getActiveBatch(farmId: String): Result<Batch?> = withContext(Dispatchers.IO) {
        try {
            val api = getApi() ?: throw Exception("API not initialized.")
            val response = api.getActiveBatch(farmId)
            if (response.status == "success") {
                cacheManager.cacheActiveBatch(response.data)
                Result.success(response.data)
            } else {
                // If backend returns 404 (or no active batch found message), return null
                cacheManager.cacheActiveBatch(null)
                Result.success(null)
            }
        } catch (e: retrofit2.HttpException) {
            if (e.code() == 404) {
                Log.d("BatchRepository", "Active batch not found on server (404). Clearing cache.")
                cacheManager.cacheActiveBatch(null)
                Result.success(null)
            } else {
                Log.w("BatchRepository", "HTTP error fetching active batch: ${e.code()}. Loading cached data.")
                val cachedBatch = cacheManager.getCachedActiveBatch()
                Result.success(cachedBatch)
            }
        } catch (e: java.io.IOException) {
            Log.w("BatchRepository", "Network offline fetching active batch; loading cached data: ${e.localizedMessage}")
            val cachedBatch = cacheManager.getCachedActiveBatch()
            Result.success(cachedBatch)
        } catch (e: Exception) {
            Log.e("BatchRepository", "Unexpected error fetching active batch: ${e.localizedMessage}")
            // Fall back to cached batch offline
            val cachedBatch = cacheManager.getCachedActiveBatch()
            Result.success(cachedBatch)
        }
    }


    suspend fun closeBatch(
        batchId: String,
        status: BatchStatus,
        endDate: String,
        currentCount: Int
    ): Result<Unit> = withContext(Dispatchers.IO) {
        try {
            val api = getApi() ?: throw Exception("API not initialized.")
            val request = CloseBatchRequest(
                status = status,
                endDate = endDate,
                currentCount = currentCount
            )
            val response = api.closeBatch(batchId, request)
            if (response.status == "success") {
                cacheManager.cacheActiveBatch(null)
                Result.success(Unit)
            } else {
                throw Exception(response.message ?: "Failed to close batch on backend.")
            }
        } catch (e: Exception) {
            Log.e("BatchRepository", "Error closing batch: ${e.localizedMessage}")
            Result.failure(e)
        }
    }

    suspend fun getAllBatches(farmId: String): Result<List<Batch>> = withContext(Dispatchers.IO) {
        try {
            val api = getApi() ?: throw Exception("API not initialized.")
            val response = api.getAllBatches(farmId)
            if (response.status == "success" && response.data != null) {
                Result.success(response.data)
            } else {
                Result.success(emptyList())
            }
        } catch (e: Exception) {
            Log.e("BatchRepository", "Error fetching batch history: ${e.localizedMessage}")
            Result.failure(e)
        }
    }

    suspend fun getUnsyncedMortalityCount(batchId: String): Int = withContext(Dispatchers.IO) {
        mortalityDao.getUnsyncedMortalityCountForBatch(batchId) ?: 0
    }

    suspend fun recordMortality(
        batchId: String,
        deathCount: Int,
        reason: String,
        notes: String?,
        recordedBy: String
    ): Result<Batch> = withContext(Dispatchers.IO) {
        try {
            val cachedBatch = cacheManager.getCachedActiveBatch()
            if (cachedBatch == null || cachedBatch.id != batchId) {
                throw Exception("Active batch not found in local cache.")
            }
            if (deathCount > cachedBatch.currentCount) {
                throw Exception("Mortality count ($deathCount) cannot exceed current batch count (${cachedBatch.currentCount}).")
            }

            val record = com.poultryguard.ai.data.model.MortalityRecord(
                id = UUID.randomUUID().toString(),
                deathCount = deathCount,
                reason = reason,
                notes = notes,
                timestamp = System.currentTimeMillis(),
                recordedBy = recordedBy,
                symptoms = notes ?: "Unspecified",
                suspectedCause = reason,
                batchId = batchId,
                isSynced = false
            )

            val api = getApi()
            if (api != null) {
                val response = api.recordMortality(
                    batchId = batchId,
                    body = RecordMortalityRequest(
                        id = record.id,
                        deathCount = record.deathCount,
                        reason = record.reason,
                        notes = record.notes,
                        recordedAt = record.timestamp,
                        recordedBy = record.recordedBy
                    )
                )
                if (response.status == "success" && response.data != null) {
                    val updatedBatch = response.data
                    cacheManager.cacheActiveBatch(updatedBatch)
                    val syncedRecord = record.copy(isSynced = true)
                    mortalityDao.insert(syncedRecord)
                    return@withContext Result.success(updatedBatch)
                } else {
                    throw Exception(response.message ?: "Server rejected mortality event.")
                }
            } else {
                mortalityDao.insert(record)
                return@withContext Result.success(cachedBatch)
            }
        } catch (e: Exception) {
            Log.e("BatchRepository", "Failed to record batch mortality: ${e.localizedMessage}")
            Result.failure(e)
        }
    }

    /**
     * Outbox Sync Engine: synchronizes local offline mortality events to the server.
     */
    suspend fun syncUnsyncedMortalities(): Result<Unit> = withContext(Dispatchers.IO) {
        try {
            val api = getApi() ?: return@withContext Result.failure(Exception("API not initialized"))
            val unsynced = mortalityDao.getUnsyncedRecords()
            if (unsynced.isEmpty()) {
                return@withContext Result.success(Unit)
            }
            
            var successCount = 0
            for (record in unsynced) {
                val bId = record.batchId
                if (bId != null) {
                    try {
                        val response = api.recordMortality(
                            batchId = bId,
                            body = RecordMortalityRequest(
                                id = record.id,
                                deathCount = record.deathCount,
                                reason = record.reason,
                                notes = record.notes,
                                recordedAt = record.timestamp,
                                recordedBy = record.recordedBy
                            )
                        )
                        if (response.status == "success") {
                            mortalityDao.markAsSynced(record.id)
                            successCount++
                            response.data?.let { cacheManager.cacheActiveBatch(it) }
                            Log.d("BatchRepository", "Successfully synced mortality record: ${record.id}")
                        }
                    } catch (e: Exception) {
                        Log.w("BatchRepository", "Failed to sync mortality record ${record.id}: ${e.localizedMessage}")
                    }
                }
            }
            Result.success(Unit)
        } catch (e: Exception) {
            Log.e("BatchRepository", "Error in syncUnsyncedMortalities: ${e.localizedMessage}")
            Result.failure(e)
        }
    }
}
